Feat/styles
katerinamartysko/book pull request #17
Opened 2022-12-29 10:58 UTC by katerinamartysko

2022-12-29 11:01 UTC, katerinamartysko commented
![](https://github.trello.services/images/mini-trello-icon.png) [Support abbreviation avatars if it doesn't exist](https://trello.com/c/9pt1HUGH/16-support-abbreviation-avatars-if-it-doesnt-exist)

2023-01-09 19:19 UTC, LexaLukovka requested changes

2023-01-09 19:19 UTC, LexaLukovka commented on src/components/ClientId.tsx
> +        {clientIdError && <h1 className="error">Произошла ошибка {clientIdError}</h1>}
Please use `Typography` variant h1

2023-01-09 19:19 UTC, LexaLukovka commented on src/components/ClientsListContainer.tsx
>    if (clientError) return <h1 className="error">Произошла ошибка {clientError}</h1>;
Please use `Typography`

2023-01-09 19:19 UTC, LexaLukovka commented on src/components/Search.tsx
> +    [theme.breakpoints.up('lg')]: {
remove unnecessary styles

2023-01-09 19:19 UTC, LexaLukovka commented on src/utils/getFirstLetters.ts
>  export const getFirstLetters = (general: General): string => {
Please receive object with first and last name not a `general: General`

2023-01-10 09:25 UTC, katerinamartysko commented on src/components/ClientId.tsx
> +        {clientIdError && <h1 className="error">Произошла ошибка {clientIdError}</h1>}
Done

2023-01-10 09:26 UTC, katerinamartysko commented on src/components/ClientsListContainer.tsx
>    if (clientError) return <h1 className="error">Произошла ошибка {clientError}</h1>;
Done

2023-01-10 09:26 UTC, katerinamartysko commented on src/components/Search.tsx
> +    [theme.breakpoints.up('lg')]: {
Done

2023-01-10 09:26 UTC, katerinamartysko commented on src/utils/getFirstLetters.ts
>  export const getFirstLetters = (general: General): string => {
Done

2023-01-10 09:35 UTC, LexaLukovka approved these changes

2023-01-10 09:35 UTC, merged